'use strict';
const $ = sel => document.querySelector(sel);
const $$ = sel => Array.from(document.querySelectorAll(sel));
const APP_VERSION = 'PMM Pocket Web v0.1 beta';
const state = { data:null, fileName:'pmm_data.json', fileHandle:null, dirty:false, edit:{type:null,id:null,index:null}, photoTarget:null, crop:{img:null,scale:1,rotation:0,dx:0,dy:0,drag:false,lastX:0,lastY:0} };
const typeLabels = ['P','PS','K','KS','K（要フォロー）','KS（要フォロー）'];
const titleOptions = ['','ONE','GM','PM','ECM','DCM','PDCM'];
const genderOptions = ['','男性','女性','その他'];
const genOptions = ['','20代','30代','40代','50代','60代','70代'];
const progressFlags = [
  ['activity_flag_pbtest','PB試験'],['activity_flag_3kuchi','3口'],['activity_flag_be','BE'],['activity_flag_pbs','PBS'],
  ['activity_flag_dreamlist','夢リスト'],['activity_flag_sevenbridge','センスオブブリッジ'],['activity_flag_listup','リストアップ'],['activity_flag_awpgrad','AWP卒業']
];
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
function uid(){return (crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)).replace(/-/g,'')}
function markDirty(v=true){state.dirty=v; $('#dirtyMark').textContent=v?'未書き出し':''}
function escapeHtml(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function photoSrc(b64){if(!b64)return ''; if(String(b64).startsWith('data:'))return b64; return 'data:image/jpeg;base64,'+b64}
function stripDataUrl(s){return String(s||'').replace(/^data:image\/\w+;base64,/, '')}
function membersArray(){if(!state.data?.members)return[];return Object.values(state.data.members).filter(m=>!m.removed && !m.deleted)}
function emptyData(){return {root_id:null,members:{},other_members:[],pending_self_members:[]}}
function normalizeData(d){d=d||emptyData(); d.members=d.members||{}; d.other_members=Array.isArray(d.other_members)?d.other_members:[]; d.pending_self_members=Array.isArray(d.pending_self_members)?d.pending_self_members:[]; d.other_members.forEach(o=>{if(!o.id)o.id=uid()}); d.pending_self_members.forEach(p=>{if(!p.pending_id)p.pending_id=uid()}); return d}
async function readJsonFile(file){const txt=await file.text(); const data=normalizeData(JSON.parse(txt)); state.data=data; state.fileName=file.name||'pmm_data.json'; state.fileHandle=null; $('#loadedName').textContent=state.fileName; $('#startView').classList.add('hidden'); $('#mainView').classList.remove('hidden'); markDirty(false); renderAll(); toast('読み込みました')}
async function writeJson(){if(!state.data){toast('データがありません');return}
  const blob = new Blob([JSON.stringify(state.data,null,2)],{type:'application/json'});
  if(window.showSaveFilePicker){
    try{
      const handle = await showSaveFilePicker({suggestedName:state.fileName,types:[{description:'PMM JSON',accept:{'application/json':['.json']}}]});
      const w=await handle.createWritable(); await w.write(blob); await w.close(); markDirty(false); toast('保存しました'); return;
    }catch(e){ if(e.name==='AbortError') return; console.warn(e); }
  }
  const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=state.fileName||'pmm_data.json'; document.body.appendChild(a); a.click(); a.remove(); setTimeout(()=>URL.revokeObjectURL(a.href),5000); markDirty(false); toast('書き出しました')
}
function renderAll(){renderSelf();renderOther();renderPending();}
function makeAvatar(b64,name,large=false){const src=photoSrc(b64); if(src){return `<img class="avatar ${large?'large':''}" src="${src}" alt="" data-preview="${escapeHtml(src)}">`} return `<div class="avatar ${large?'large':''}">${escapeHtml((name||'?').slice(0,1))}</div>`}
function typeTag(t){const cls=String(t||'').toLowerCase().replace(/[（）]/g,'');return `<span class="tag ${cls}">${escapeHtml(t||'-')}</span>`}
function searchText(obj,keys){return keys.map(k=>obj?.[k]||'').join(' ').toLowerCase()}
function renderSelf(){const q=($('#selfSearch')?.value||'').trim().toLowerCase();const list=$('#selfList'); if(!list)return; let rows=membersArray(); rows=rows.filter(m=>['P','PS','K','KS','K（要フォロー）','KS（要フォロー）'].includes(m.member_type||'') || true); rows=rows.filter(m=>!q||searchText(m,['name','member_type','introducer_name','profile_region','profile_role','memo','activity_promise','activity_next_action','activity_next_date','activity_event','activity_temperature','activity_note']).includes(q)); $('#selfCount').textContent=`${rows.length}件`; list.innerHTML=rows.map(m=>`<article class="member-card" data-self-id="${m.id}">${makeAvatar(m.photo_data,m.name)}<div class="card-main"><div class="card-title">${escapeHtml(m.name)}</div><div class="card-meta">${typeTag(m.member_type)} ${escapeHtml(m.profile_region||'')} ${escapeHtml(m.profile_role||'')}<br>${escapeHtml(m.activity_next_action||'')}${m.activity_next_date?' / '+escapeHtml(m.activity_next_date):''}</div></div><div class="card-actions"><button class="secondary-btn small" data-edit-self="${m.id}">編集</button></div></article>`).join('')||'<p class="notice">該当なし</p>'}
function renderOther(){const q=($('#otherSearch')?.value||'').trim().toLowerCase(); const rows=(state.data?.other_members||[]).filter(o=>!q||searchText(o,['name','team','team2','team3','role','region','gender','generation','note']).includes(q)); $('#otherCount').textContent=`${rows.length}件`; $('#otherList').innerHTML=rows.map((o,i)=>`<article class="member-card"><div data-preview-wrap>${makeAvatar(o.photo_data,o.name)}</div><div class="card-main"><div class="card-title">${escapeHtml(o.name)}</div><div class="card-meta">${escapeHtml([o.team,o.team2,o.team3].filter(Boolean).join(' / ')||'-')}<br>${escapeHtml([o.role,o.region,o.gender,o.generation].filter(Boolean).join(' / '))}</div></div><div class="card-actions"><button class="secondary-btn small" data-edit-other="${i}">編集</button></div></article>`).join('')||'<p class="notice">該当なし</p>'}
function renderPending(){const q=($('#pendingSearch')?.value||'').trim().toLowerCase(); const rows=(state.data?.pending_self_members||[]).filter(p=>!q||searchText(p,['name','member_type','introducer_name','region','title','memo','activity_memo','status','next_action','next_action_date','event']).includes(q)); $('#pendingCount').textContent=`${rows.length}件`; $('#pendingList').innerHTML=rows.map((p,i)=>`<article class="member-card">${makeAvatar(p.photo_data,p.name)}<div class="card-main"><div class="card-title">${escapeHtml(p.name)}</div><div class="card-meta">${typeTag(p.member_type)} 紹介者: ${escapeHtml(p.introducer_name||'-')}<br>${escapeHtml([p.region,p.title,p.next_action,p.next_action_date].filter(Boolean).join(' / '))}</div></div><div class="card-actions"><button class="secondary-btn small" data-edit-pending="${i}">編集</button></div></article>`).join('')||'<p class="notice">該当なし</p>'}
function formInput(label,name,value='',type='text'){return `<div class="form-row"><label>${label}</label><input name="${name}" type="${type}" value="${escapeHtml(value)}"></div>`}
function formText(label,name,value=''){return `<div class="form-row"><label>${label}</label><textarea name="${name}">${escapeHtml(value)}</textarea></div>`}
function formSelect(label,name,value='',opts=[]){return `<div class="form-row"><label>${label}</label><select name="${name}">${opts.map(o=>`<option value="${escapeHtml(o)}" ${o===value?'selected':''}>${escapeHtml(o||' ')}</option>`).join('')}</select></div>`}
function progressHtml(obj){return `<div class="form-row"><label>進捗チェック</label><div class="checks">${progressFlags.map(([k,l])=>`<label><input type="checkbox" name="${k}" ${obj?.[k]?'checked':''}> ${l}</label>`).join('')}</div></div>`}
function photoBlock(obj){return `<div class="photo-row">${makeAvatar(obj.photo_data,obj.name,true)}<div class="photo-actions"><button type="button" class="secondary-btn small" id="photoEditBtn">写真登録</button><button type="button" class="danger-btn small" id="photoRemoveBtn">写真削除</button></div></div>`}
function openEdit(type,idOrIndex){state.edit={type,id:null,index:null}; let obj={}; if(type==='self'){state.edit.id=idOrIndex; obj=state.data.members[idOrIndex]||{}} if(type==='other'){state.edit.index=Number(idOrIndex); obj=state.data.other_members[state.edit.index]||{}} if(type==='pending'){state.edit.index=Number(idOrIndex); obj=state.data.pending_self_members[state.edit.index]||{}} if(type==='other-new'){obj={id:uid(),name:''}} if(type==='pending-new'){obj={pending_id:uid(),name:'',member_type:'P',created_at:new Date().toISOString().slice(0,19)}}
  $('#editTitle').textContent= type.includes('other')?'他メンバー':type.includes('pending')?'新メンバー':'自メンバー';
  $('#deleteBtn').classList.toggle('hidden', type==='self' || type.endsWith('new'));
  let html=photoBlock(obj);
  if(type==='self') html += `<div class="two-col">${formInput('名前','name',obj.name)}${formSelect('メンバー種類','member_type',obj.member_type,typeLabels)}${formInput('紹介者名','introducer_name',obj.introducer_name)}${formInput('地域','profile_region',obj.profile_region)}${formInput('タイトル','profile_role',obj.profile_role)}</div>${progressHtml(obj)}<h4>活動管理</h4>${formInput('約束したこと','activity_promise',obj.activity_promise)}${formInput('次回アクション','activity_next_action',obj.activity_next_action)}${formInput('次回予定日','activity_next_date',obj.activity_next_date,'date')}${formInput('参加予定イベント','activity_event',obj.activity_event)}${formInput('温度感','activity_temperature',obj.activity_temperature)}${formText('活動メモ','activity_note',obj.activity_note)}`;
  else if(type.includes('other')) html += `${formInput('名前','name',obj.name)}<div class="two-col">${formInput('所属チーム1','team',obj.team)}${formInput('所属チーム2','team2',obj.team2)}${formInput('所属チーム3','team3',obj.team3)}${formSelect('タイトル','role',obj.role,titleOptions)}${formInput('地域','region',obj.region)}${formSelect('性別','gender',obj.gender,genderOptions)}${formSelect('世代','generation',obj.generation,genOptions)}</div>${formText('メモ','note',obj.note)}`;
  else html += `<div class="two-col">${formInput('名前','name',obj.name)}${formSelect('メンバー種類','member_type',obj.member_type,typeLabels)}${formInput('紹介者名','introducer_name',obj.introducer_name)}${formInput('地域','region',obj.region)}${formInput('タイトル','title',obj.title)}</div>${progressHtml(obj)}<h4>活動管理</h4>${formInput('約束したこと','promise',obj.promise||obj.activity_promise)}${formInput('次回アクション','next_action',obj.next_action)}${formInput('次回予定日','next_action_date',obj.next_action_date,'date')}${formInput('参加予定イベント','event',obj.event)}${formInput('温度感','temperature',obj.temperature)}${formText('活動メモ','activity_memo',obj.activity_memo||obj.memo)}`;
  $('#editBody').innerHTML=html; $('#editDialog').showModal();
}
function saveEdit(){const fd=new FormData($('#editForm')); const type=state.edit.type; let obj={}; if(type==='self') obj=state.data.members[state.edit.id]; else if(type==='other') obj=state.data.other_members[state.edit.index]; else if(type==='pending') obj=state.data.pending_self_members[state.edit.index]; else obj={};
  for(const [k,v] of fd.entries()) obj[k]=String(v);
  progressFlags.forEach(([k])=>{obj[k]=!!$('#editBody').querySelector(`[name="${k}"]`)?.checked});
  if(type==='other-new'){ if(!obj.id)obj.id=uid(); state.data.other_members.push(obj); }
  if(type==='pending-new'){ if(!obj.pending_id)obj.pending_id=uid(); if(!obj.created_at)obj.created_at=new Date().toISOString().slice(0,19); obj.source='PMM Pocket Web'; state.data.pending_self_members.push(obj); }
  markDirty(); renderAll(); $('#editDialog').close(); toast('保存しました。最後にJSON書き出ししてください')
}
function deleteEdit(){const type=state.edit.type;if(type==='other')state.data.other_members.splice(state.edit.index,1); if(type==='pending')state.data.pending_self_members.splice(state.edit.index,1); markDirty();renderAll();$('#editDialog').close();toast('削除しました')}
function openPhoto(){state.photoTarget={...state.edit}; resetCrop(); $('#photoDialog').showModal(); drawCrop()}
function resetCrop(){state.crop={img:null,scale:1,rotation:0,dx:0,dy:0,drag:false,lastX:0,lastY:0}; $('#zoomRange').value=1}
function getCurrentObj(){const t=state.edit.type;if(t==='self')return state.data.members[state.edit.id]; if(t==='other')return state.data.other_members[state.edit.index]; if(t==='pending')return state.data.pending_self_members[state.edit.index]; return null}
function setCurrentPhoto(b64){const obj=getCurrentObj(); if(obj){obj.photo_data=b64; markDirty(); renderAll();}}
function loadCropFile(file){if(!file)return; const img=new Image(); img.onload=()=>{state.crop.img=img; state.crop.scale=Math.max(320/img.width,320/img.height); $('#zoomRange').value=state.crop.scale; state.crop.dx=0; state.crop.dy=0; drawCrop()}; img.src=URL.createObjectURL(file)}
function drawCrop(){const c=$('#cropCanvas'),ctx=c.getContext('2d'),cr=state.crop; ctx.clearRect(0,0,c.width,c.height); ctx.fillStyle='#111';ctx.fillRect(0,0,c.width,c.height); if(!cr.img)return; ctx.save(); ctx.translate(c.width/2+cr.dx,c.height/2+cr.dy); ctx.rotate(cr.rotation*Math.PI/180); ctx.scale(cr.scale,cr.scale); ctx.drawImage(cr.img,-cr.img.width/2,-cr.img.height/2); ctx.restore()}
function applyPhoto(){const src=$('#cropCanvas'); const out=document.createElement('canvas'); out.width=160; out.height=160; const o=out.getContext('2d'); o.drawImage(src,40,40,240,240,0,0,160,160); setCurrentPhoto(stripDataUrl(out.toDataURL('image/jpeg',0.72))); $('#photoDialog').close(); $('#editDialog').close(); toast('写真を登録しました。JSON書き出ししてください')}
function preview(src){if(!src)return; $('#previewImage').src=src; $('#previewDialog').showModal()}
function showInfo(kind){const help=`<p><strong>使い方</strong></p><ol><li>PMM本体を閉じます</li><li>JSON読込でPMM保存ファイルを読み込みます</li><li>自メンバー活動管理や他メンバー辞書を編集します</li><li>最後にJSON書き出しで保存します</li><li>PMM本体で書き出したJSONを開きます</li></ol><p>このWeb版はデータをサーバーへ保存しません。読み込んだJSONはブラウザ内で処理します。</p>`;
 const about=`<p><strong>PMM Pocket Web</strong><br>${APP_VERSION}</p><p>PMM本体で作成したJSONをスマホやPCブラウザで確認・編集する補助ツールです。</p><p>お問い合わせ先：兵藤 茂樹<br>LINE: https://line.me/ti/p/XJt7xbeJ1j</p>`;
 $('#infoTitle').textContent=kind==='help'?'ヘルプ':'このアプリについて'; $('#infoBody').innerHTML=kind==='help'?help:about; $('#infoDialog').showModal(); }
function init(){ if(localStorage.getItem('pmmPocketDark')==='1')document.body.classList.add('dark'); $('#darkToggle').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('pmmPocketDark',document.body.classList.contains('dark')?'1':'0')};
 ['fileInput','fileInput2'].forEach(id=>{$('#'+id).onchange=e=>{const f=e.target.files[0]; if(!f)return; alert('保存ファイルの読み込み\n\nPMM本体とPMM Pocket Webで同じ保存ファイルを同時に開くと 上書き事故の原因になります。\n\nPMM本体を閉じてから読み込んでください。'); readJsonFile(f); e.target.value='';}});
 $('#newDataBtn').onclick=()=>{state.data=emptyData();state.fileName='pmm_data.json';$('#loadedName').textContent=state.fileName;$('#startView').classList.add('hidden');$('#mainView').classList.remove('hidden');renderAll();markDirty(false)}; $('#saveBtn').onclick=writeJson;
 $$('.tab').forEach(b=>b.onclick=()=>{$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('.tab-view').forEach(v=>v.classList.remove('active'));$('#tab-'+b.dataset.tab).classList.add('active')});
 $('#selfSearch').oninput=renderSelf; $('#otherSearch').oninput=renderOther; $('#pendingSearch').oninput=renderPending; $('#otherAddBtn').onclick=()=>openEdit('other-new'); $('#pendingAddBtn').onclick=()=>openEdit('pending-new');
 document.body.addEventListener('click',e=>{const p=e.target.closest('[data-preview]'); if(p) preview(p.dataset.preview); const s=e.target.closest('[data-edit-self]'); if(s)openEdit('self',s.dataset.editSelf); const o=e.target.closest('[data-edit-other]'); if(o)openEdit('other',o.dataset.editOther); const pn=e.target.closest('[data-edit-pending]'); if(pn)openEdit('pending',pn.dataset.editPending); const l=e.target.closest('[data-dialog]'); if(l)showInfo(l.dataset.dialog);});
 $('#closeEditBtn').onclick=()=>$('#editDialog').close(); $('#editSaveBtn').onclick=saveEdit; $('#deleteBtn').onclick=deleteEdit; $('#closeInfoBtn').onclick=()=>$('#infoDialog').close(); $('#closePreviewBtn').onclick=()=>$('#previewDialog').close();
 document.addEventListener('click',e=>{ if(e.target?.id==='photoEditBtn')openPhoto(); if(e.target?.id==='photoRemoveBtn'){setCurrentPhoto(''); $('#editDialog').close(); toast('写真を削除しました')}});
 $('#closePhotoBtn').onclick=()=>$('#photoDialog').close(); $('#photoFileInput').onchange=e=>loadCropFile(e.target.files[0]); $('#photoCameraInput').onchange=e=>loadCropFile(e.target.files[0]); $('#rotatePhotoBtn').onclick=()=>{state.crop.rotation=(state.crop.rotation+90)%360;drawCrop()}; $('#clearPhotoBtn').onclick=()=>{setCurrentPhoto('');$('#photoDialog').close();$('#editDialog').close();toast('写真を削除しました')}; $('#applyPhotoBtn').onclick=applyPhoto; $('#zoomRange').oninput=e=>{state.crop.scale=Number(e.target.value);drawCrop()};
 const cw=$('.crop-wrap'); cw.addEventListener('pointerdown',e=>{state.crop.drag=true;state.crop.lastX=e.clientX;state.crop.lastY=e.clientY;cw.setPointerCapture(e.pointerId)}); cw.addEventListener('pointermove',e=>{if(!state.crop.drag)return;state.crop.dx+=e.clientX-state.crop.lastX;state.crop.dy+=e.clientY-state.crop.lastY;state.crop.lastX=e.clientX;state.crop.lastY=e.clientY;drawCrop()}); cw.addEventListener('pointerup',()=>state.crop.drag=false);
 if('serviceWorker' in navigator){navigator.serviceWorker.register('./sw.js').catch(()=>{})}
}
document.addEventListener('DOMContentLoaded',init);
